---
# Playbook to build Docker images for this project.

- hosts: localhost
  sudo: no

  vars:
    dev: false
    docker_owner: "hajaalin"
    omero_components:
      - omero-base
      - omero
      - omero-initdb
      - omero-hyldap
      - omero-web
      - omero-nginx
      - omero-postgres
      - backup
    volume_pg_dump: "/home/hajaalin/tmp/pg_dump"

  tasks:
  - name: read the current Git branch
    shell: git branch -v|grep "\*"|awk '{print $2}'
    register: git_branch

  - name: read the current Git commit
    shell: git log |head -1|awk '{print $2}'
    register: git_commit

  - set_fact: docker_tag="{{ git_branch.stdout }}-{{ git_commit.stdout }}"

  - name: tag images as "DEV" in dev environment
    set_fact: docker_tag="DEV"
    when: dev

  - debug: var=docker_tag

  - name: template Dockerfiles
    template:
      src="{{ item }}/Dockerfile.j2"
      dest="{{ item }}/Dockerfile"
    with_items: "{{ omero_components }}"

  - name: build images
    docker_image:
      path="./{{ item }}"
      name="{{ docker_owner }}/{{ item }}"
      tag="{{ docker_tag }}"
      state=build
    with_items: "{{ omero_components }}"

  - name: template compose file
    template:
      src="compose/compose.yml.j2"
      dest="compose/compose-{{ docker_tag }}.yml"
