FROM ubuntu:14.04

RUN sed 's/main$/main universe/' -i /etc/apt/sources.list

RUN apt-get update && \
apt-get -y install \
  unzip \
  wget \
  python-imaging \
  python-matplotlib \
  python-numpy \
  python-pip \
  python-scipy \
  python-tables \
  python-virtualenv \
  openjdk-7-jre-headless \
  ice-services python-zeroc-ice \
  postgresql-client-9.3 \
  supervisor \
  vim \
  sudo

RUN useradd -m omero
RUN su - omero -c "virtualenv --system-site-packages ~/venv"
RUN su - omero -c "~/venv/bin/pip install -U yaclifw && ~/venv/bin/pip install -U omego"

RUN echo "Dummy change"
