FROM {{ docker_owner }}/omero:{{ docker_tag }}

USER root
RUN mkdir /initdb \
&& chown omero:omero /initdb

VOLUME /initdb

USER omero

WORKDIR /home/omero
ENV script create_initdb_script.sh
COPY $script /home/omero/
 
ENTRYPOINT /bin/sh -c
CMD $script

