FROM {{ docker_owner }}/omero:{{ docker_tag }}

USER root

RUN apt-get install -y ldap-utils 

ENV OMERO_TRUSTSTORE /home/omero/truststore.jks

COPY set_config_hyldap.sh /set_config_hyldap.sh
COPY create_truststore.sh /create_truststore.sh
COPY hyldapConfig.xml /home/omero/hyldapConfig.xml
COPY hyldap-5.1.1-328-f978880-ice35-b0.jar /opt/omero/lib/server/extensions.jar
COPY logback.xml /opt/omero/etc/logback.xml
RUN chown omero:omero /*.sh \
&& chown omero:omero /home/omero/hyldapConfig.xml \
&& chown omero:omero /opt/omero/lib/server/extensions.jar \
&& chown omero:omero /opt/omero/etc/logback.xml

USER omero

RUN omero config set omero.security.trustStore $OMERO_TRUSTSTORE \
&& omero config set omero.ldap.config true \
&& omero config set omero.ldap.base dc=helsinki,dc=fi \
&& omero config set omero.ldap.user_mapping 'omeName=uid,firstName=givenName,lastName=sn,email=uid' \
&& omero config set omero.ldap.new_user_group ':bean:hyldapbean' \
&& omero config set omero.ldap.sync_on_login false \
&& echo "hyldap.config=/home/omero/hyldapConfig.xml" >> /opt/omero/etc/omero.properties

RUN echo "dummy change" > /home/omero/dummychange
