#!/bin/sh
### BEGIN INIT INFO
# Provides: fig-omero-test1
# Required-Start: $local_fs $network $named $time $syslog
# Required-Stop: $local_fs $network $named $time $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: <DESCRIPTION>
### END INIT INFO
 
START='cd /opt/GitHub/fig-omero-test1; . make_env.sh; fig up -d'
STOP='cd /opt/GitHub/fig-omero-test1; . make_env.sh; fig stop'
RUNAS=root
 
PIDFILE=/var/run/fig-omero-test1.pid
LOGFILE=/var/log/fig-omero-test1.log
 
start() {
if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
echo 'Service already running' >&2
return 1
fi
echo 'Starting service…' >&2
local CMD="$START &> \"$LOGFILE\" & echo \$!"
su -c "$CMD" $RUNAS > "$PIDFILE"
echo 'Service started' >&2
}
 
stop() {
#if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
#echo 'Service not running' >&2
#return 1
#fi
echo 'Stopping service…' >&2
local CMD="$STOP &>> \"$LOGFILE\""
su -c "$CMD" $RUNAS
#kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
echo 'Service stopped' >&2
}
 
uninstall() {
echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
local SURE
read SURE
if [ "$SURE" = "yes" ]; then
stop
rm -f "$PIDFILE"
echo "Notice: log file is not be removed: '$LOGFILE'" >&2
update-rc.d -f fig-omero-test1 remove
rm -fv "$0"
fi
}
 
case "$1" in
start)
start
;;
stop)
stop
;;
uninstall)
uninstall
;;
restart)
stop
start
;;
*)
echo "Usage: $0 {start|stop|restart|uninstall}"
esac

